# Generated by Django 2.1.1 on 2018-12-21 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(default='', max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30, null=True)),
                ('image', models.FileField(blank=True, null=True, upload_to='')),
                ('account_no', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('active', models.BooleanField(default=False)),
            ],
        ),
    ]
