# Generated by Django 2.1.1 on 2019-01-03 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appone', '0002_auto_20181222_0820'),
    ]

    operations = [
        migrations.CreateModel(
            name='currentbill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billno', models.IntegerField(auto_created=True)),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appone.customer')),
            ],
        ),
    ]
