# Generated by Django 2.1.1 on 2019-01-03 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appone', '0003_currentbill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentbill',
            name='billno',
            field=models.IntegerField(max_length=10),
        ),
    ]
