# Generated by Django 2.1.1 on 2019-01-03 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appone', '0004_auto_20190103_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentbill',
            name='billno',
            field=models.IntegerField(),
        ),
    ]
