# Generated by Django 2.1.1 on 2019-01-06 09:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('appone', '0006_auto_20190105_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountinfo',
            name='account_password',
            field=models.CharField(default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
    ]
