# Generated by Django 2.1.1 on 2019-01-06 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appone', '0008_auto_20190106_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentbill',
            name='billno',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='paidcurrent',
            name='billno',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='unpaidcurrent',
            name='billno',
            field=models.CharField(max_length=30),
        ),
    ]
